"""Full-sample / broken-Sigma diagnostics and the auto-generated findings report.

Everything in ``results/key_findings.md`` is computed from the result tables at
run time; no number is typed in by hand.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from . import config, covariance as cv, linalg_tools as lt, optimize as op


def full_sample_report(returns: pd.DataFrame) -> dict:
    """Eigenvalue summary, inertia, condition number, PD check of the sample Sigma."""
    S = cv.sample_cov(returns)
    N, T = returns.shape[1], len(returns)
    vals, _ = lt.eig_decompose(S)
    edge = lt.mp_noise_edge(N, T, np.trace(S) / N)
    return dict(T=T, N=N, lambda_min=float(vals[0]), lambda_median=float(np.median(vals)),
                lambda_max=float(vals[-1]), top1_variance_share=float(vals[-1] / vals.sum()),
                inertia=lt.inertia(S), condition_number=lt.condition_number(S),
                positive_definite=lt.is_positive_definite(S), mp_edge=float(edge),
                n_above_mp_edge=int(np.sum(vals > edge)))


def short_window_report(returns: pd.DataFrame) -> pd.DataFrame:
    """Scenario (a): sample cov from the first T rows, T from below N to above N.

    Columns compare ``np.linalg.solve`` with the truncated spectral inverse.
    ``solve`` results for exactly singular S depend on BLAS/rounding and may
    differ between platforms; inertia and spectral weights do not.
    """
    N = returns.shape[1]
    rows = []
    for T in sorted({N // 2, N - 1, N, N + 1, 2 * N, *config.WINDOWS}):
        if T > len(returns):
            continue
        S, (p, z, n) = cv.short_window_cov(returns, T)
        try:
            max_w, solve_ok = float(np.abs(op.min_variance_closed_form(S)).max()), True
        except np.linalg.LinAlgError:
            max_w, solve_ok = float("nan"), False
        w_s = lt.min_variance_weights_spectral(S)
        rows.append(dict(T=T, N=N, n_pos=p, n_zero=z, n_neg=n,
                         pd_cholesky=lt.is_positive_definite(S), cond=lt.condition_number(S),
                         solve_ok=solve_ok, max_abs_w_solve=max_w,
                         max_abs_w_spectral=float(np.abs(w_s).max())))
    return pd.DataFrame(rows)


def md_table(df: pd.DataFrame, fmt: str = "{:.4g}") -> str:
    """Render a DataFrame as a GitHub-markdown table (no extra dependencies)."""
    def cell(v):
        return fmt.format(v) if isinstance(v, (float, np.floating)) else str(v)
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(cell(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *body])


def write_key_findings(path, full: dict, dropped: list[str], short: pd.DataFrame,
                       missing: pd.DataFrame, summary: pd.DataFrame,
                       expo: pd.DataFrame, n_runs: int) -> str:
    """Write results/key_findings.md from the computed tables; returns the text."""
    L = ["# Key findings (auto-generated by run_all.py)", "",
         "Every number below was computed in this run from the tables in `results/`. "
         "Risks are annualised (`std * sqrt(252)`, log returns).", "",
         "## Full-sample covariance", "",
         f"- T = {full['T']} days, N = {full['N']} stocks; dropped tickers: {dropped or 'none'}",
         f"- inertia (n_pos, n_zero, n_neg) = {full['inertia']}; positive definite (Cholesky): "
         f"{full['positive_definite']}; condition number = {full['condition_number']:.1f}",
         f"- eigenvalues: min {full['lambda_min']:.3g}, median {full['lambda_median']:.3g}, "
         f"max {full['lambda_max']:.3g}; top eigenvalue carries {100*full['top1_variance_share']:.1f}% of variance",
         f"- Marchenko-Pastur edge {full['mp_edge']:.3g}; {full['n_above_mp_edge']} eigenvalues above it", "",
         "## Scenario (a): short windows (T vs N)", "",
         md_table(short[["T", "n_pos", "n_zero", "n_neg", "pd_cholesky", "cond", "max_abs_w_solve",
                         "max_abs_w_spectral"]]), "",
         "`max_abs_w_solve` for singular windows is platform-dependent (see README).", "",
         "## Scenario (b): random masking + pairwise-complete covariance", ""]
    g = missing.groupby("mask_frac").agg(runs=("seed", "size"), non_psd=("non_psd", "sum"),
                                         lambda_min_min=("lambda_min", "min")).reset_index()
    L += [md_table(g), "",
          f"Non-PSD outcomes across all {len(missing)} runs: {int(missing.non_psd.sum())}.", ""]

    L += [f"## Rolling backtest ({n_runs} runs)", ""]
    for cons in config.CONSTRAINTS:
        s = summary[summary.constraint == cons]
        piv = lambda col: s.pivot(index="window", columns="method", values=col)[list(config.METHODS)]
        L += [f"### {cons}: mean risk gap (realised - predicted), annualised, in percentage points", "",
              md_table((piv("risk_gap_mean") * 100).reset_index(), "{:.2f}"), "",
              f"### {cons}: mean realised risk, annualised, %", "",
              md_table((piv("realized_risk_mean") * 100).reset_index(), "{:.2f}"), ""]
        best = piv("realized_risk_mean").idxmin(axis=1)
        L += ["Lowest mean realised risk by window: " +
              ", ".join(f"W={w}: {m}" for w, m in best.items()),
              "(Means over few runs that share training data; method differences at long windows "
              "are small and no significance test is applied.)", ""]

    L += ["## Hypothesis: noise-exposure score vs risk gap (raw Sigma)", "",
          "Spearman rho; `all` pools window lengths (confounded by window), `within` pools "
          "within-window percentile ranks. p-values are unadjusted and optimistic "
          "(overlapping training windows); there are many tests.", ""]
    keep = expo[expo.window.astype(str).isin(["all", "within"])]
    L += [md_table(keep.assign(significant_5pct=keep.p_value < 0.05), "{:.3f}"), ""]
    per = expo[~expo.window.astype(str).isin(["all", "within"])]
    n_sig = int((per.p_value < 0.05).sum())
    L += [f"Per-window tests: {n_sig} of {len(per)} have unadjusted p < 0.05 "
          f"(about {0.05*len(per):.1f} expected by chance alone). Full table: `exposure_vs_gap.csv`.", ""]
    text = "\n".join(L)
    path.write_text(text)
    return text
